apiVersion: apps/v1
kind: Deployment
metadata:
  name: hexchess-trainer
  namespace: hexchess
  labels:
    app: hexchess
    role: trainer
spec:
  replicas: 1
  strategy:
    type: Recreate  # only one trainer at a time
  selector:
    matchLabels:
      app: hexchess
      role: trainer
  template:
    metadata:
      labels:
        app: hexchess
        role: trainer
    spec:
      terminationGracePeriodSeconds: 5
      containers:
        - name: trainer
          image: ghcr.io/k15z/hexchess-zero/training:latest
          imagePullPolicy: Always
          args: ["trainer"]
          env:
            - name: SLACK_WEBHOOK_URL
              valueFrom:
                secretKeyRef:
                  name: slack-webhook
                  key: webhook-url
                  optional: true
          volumeMounts:
            - name: data
              mountPath: /app/.data
          resources:
            requests:
              memory: 8Gi
              cpu: "5"
            limits:
              memory: 13Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: hexchess-data
