apiVersion: apps/v1
kind: Deployment
metadata:
  name: hexchess-worker
  namespace: hexchess
  labels:
    app: hexchess
    role: worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hexchess
      role: worker
  template:
    metadata:
      labels:
        app: hexchess
        role: worker
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: hexchess
                  role: trainer
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 5
      containers:
        - name: worker
          image: ghcr.io/k15z/hexchess-zero/training:latest
          imagePullPolicy: Always
          args: ["worker"]
          volumeMounts:
            - name: data
              mountPath: /app/.data
          resources:
            requests:
              memory: 8Gi
              cpu: "5"
            limits:
              memory: 13Gi
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: hexchess-data
