//! Shared test position helpers.
//!
//! Provides both the legacy `play_n_moves` (depth-1 minimax) and a new
//! `generate_positions` helper that produces diverse positions by mixing
//! multiple play strategies across ply buckets.

use hexchess_engine::eval::EvalWeights;
use hexchess_engine::game::GameState;
use hexchess_engine::mcts::{HeuristicEvaluator, MctsSearch, SearchConfig};
use hexchess_engine::minimax;
use hexchess_engine::movegen::Move;

use rand::rngs::StdRng;
use rand::{Rng, SeedableRng};

/// Play `n` moves from the starting position using depth-1 search.
/// Returns `None` if the game ends before `n` moves.
pub fn play_n_moves(n: usize) -> Option<GameState> {
    let mut state = GameState::new();
    for _ in 0..n {
        if state.is_game_over() {
            return None;
        }
        match minimax::search(&mut state, 1, &EvalWeights::material_only()) {
            Some(r) => state.apply_move(r.best_move),
            None => return None,
        }
    }
    if state.is_game_over() {
        None
    } else {
        Some(state)
    }
}

// =========================================================================
// Stratified position generator
// =========================================================================

/// Strategy used to pick the next move during position generation.
#[derive(Clone, Copy, Debug)]
enum Strategy {
    /// Pick a uniformly random legal move.
    Random,
    /// Depth-1 minimax (material-only weights).
    MinimaxD1,
    /// Depth-2 minimax (material-only weights).
    MinimaxD2,
    /// 50-simulation MCTS with heuristic evaluator.
    Mcts50,
}

/// Ply-range bucket for stratified sampling.
#[derive(Clone, Copy, Debug)]
pub enum PlyBucket {
    /// Opening: plies 0–8.
    Opening,
    /// Midgame: plies 9–24.
    Midgame,
    /// Endgame: plies 25–60.
    Endgame,
}

impl PlyBucket {
    fn range(self) -> (usize, usize) {
        match self {
            PlyBucket::Opening => (0, 8),
            PlyBucket::Midgame => (9, 24),
            PlyBucket::Endgame => (25, 60),
        }
    }
}

/// Pick a move using the given strategy. Returns `None` if no move is
/// available (game over or search failure).
fn pick_move(state: &mut GameState, strategy: Strategy, rng: &mut StdRng) -> Option<Move> {
    if state.is_game_over() {
        return None;
    }
    match strategy {
        Strategy::Random => {
            let moves = state.legal_moves();
            if moves.is_empty() {
                return None;
            }
            Some(moves[rng.random_range(0..moves.len())])
        }
        Strategy::MinimaxD1 => {
            minimax::search(state, 1, &EvalWeights::material_only()).map(|r| r.best_move)
        }
        Strategy::MinimaxD2 => {
            minimax::search(state, 2, &EvalWeights::material_only()).map(|r| r.best_move)
        }
        Strategy::Mcts50 => {
            let mut mcts = MctsSearch::new(Box::new(HeuristicEvaluator::default()));
            let mut config = SearchConfig::eval();
            config.rng_seed = Some(rng.random::<u64>());
            mcts.set_config(config);
            let result = mcts.search(state, 50);
            Some(result.best_move)
        }
    }
}

/// Generate `count` non-terminal positions using a seeded mix of strategies,
/// with the target ply drawn uniformly from the given bucket range.
///
/// Each position is generated by an independent random walk from the starting
/// position, choosing a strategy uniformly at random for each ply. The walk
/// stops at the target ply (sampled uniformly from the bucket) and is
/// discarded if the game ends early.
///
/// This replaces the old depth-1-only `play_n_moves` for tests that need
/// diverse positions — openings, middlegames, and endgames all get coverage.
pub fn generate_positions(seed: u64, bucket: PlyBucket, count: usize) -> Vec<GameState> {
    let mut rng = StdRng::seed_from_u64(seed);
    let (lo, hi) = bucket.range();
    let strategies = [
        Strategy::Random,
        Strategy::MinimaxD1,
        Strategy::MinimaxD2,
        Strategy::Mcts50,
    ];

    let mut positions = Vec::with_capacity(count);
    let mut attempts = 0;
    let max_attempts = count * 20; // avoid infinite loops if most walks end early

    while positions.len() < count && attempts < max_attempts {
        attempts += 1;
        let target_ply = rng.random_range(lo..=hi);
        let mut state = GameState::new();
        let mut ok = true;

        for _ in 0..target_ply {
            let strat = strategies[rng.random_range(0..strategies.len())];
            match pick_move(&mut state, strat, &mut rng) {
                Some(mv) => state.apply_move(mv),
                None => {
                    ok = false;
                    break;
                }
            }
        }

        if ok && !state.is_game_over() {
            positions.push(state);
        }
    }

    positions
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn generate_positions_produces_requested_count() {
        let positions = generate_positions(42, PlyBucket::Opening, 10);
        assert_eq!(positions.len(), 10);
    }

    #[test]
    fn generate_positions_midgame_not_empty() {
        let positions = generate_positions(123, PlyBucket::Midgame, 5);
        assert!(!positions.is_empty());
    }

    #[test]
    fn generate_positions_deterministic() {
        let a = generate_positions(99, PlyBucket::Opening, 5);
        let b = generate_positions(99, PlyBucket::Opening, 5);
        assert_eq!(
            a.len(),
            b.len(),
            "deterministic runs should produce same count"
        );
        for (ga, gb) in a.iter().zip(b.iter()) {
            assert_eq!(ga.board.zobrist_hash, gb.board.zobrist_hash);
        }
    }

    #[test]
    fn generate_positions_diverse_hashes() {
        let positions = generate_positions(7, PlyBucket::Midgame, 20);
        let mut hashes: Vec<_> = positions.iter().map(|s| s.board.zobrist_hash).collect();
        hashes.sort();
        hashes.dedup();
        // At least 80% unique — random walks should be diverse
        assert!(
            hashes.len() >= positions.len() * 4 / 5,
            "only {}/{} unique positions",
            hashes.len(),
            positions.len()
        );
    }
}
